/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by cites
SELECT 
    city , 
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY city
ORDER BY total_customers DESC ;

-- Find total customers by gender
SELECT 
    gender , 
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC ;

-- Find total products by category
SELECT 
    category_name ,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category_name
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT 
    category_name ,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category_name 
ORDER BY avg_cost DESC ;

-- What is the total revenue generated for each category?
SELECT 
    p.category_name ,
    SUM(f.sales_amount) AS total_sales
FROM gold.fact_sales f
LEFT JOIN  gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category_name
ORDER BY total_sales DESC ;

-- What is the total revenue generated for each branch?
SELECT 
    b.branch_name ,
    SUM(f.sales_amount) AS total_sales
FROM gold.fact_sales f
LEFT JOIN  gold.dim_branches b
ON f.branch_key = b.branch_key
GROUP BY b.branch_name
ORDER BY total_sales DESC ;


-- What is the total revenue generated by each customer?
SELECT 
    c.customer_key ,
    c.first_name , 
    c.last_name , 
    SUM(f.sales_amount) AS total_sales
FROM gold.fact_sales f
LEFT JOIN  gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key , c.first_name ,c.last_name
ORDER BY total_sales DESC ;